version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - aws --version
      - curl -qL -o jq https://stedolan.github.io/jq/download/linux64/jq && chmod +x ./jq
      - curl -qL -o aws_credentials.json http://169.254.170.2/$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI > aws_credentials.json
      - aws configure set region $AWS_REGION
      - aws configure set aws_access_key_id `./jq -r '.AccessKeyId' aws_credentials.json`
      - aws configure set aws_secret_access_key `./jq -r '.SecretAccessKey' aws_credentials.json`
      - aws configure set aws_session_token `./jq -r '.Token' aws_credentials.json`
      - ./rke.sh init
      - python3 --version
      - IFS=
      - ./rke.sh run 2>&1 | tee -a rke.log
      - echo Build completed on `date`
artifacts:
  files:
    - rke.log