version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - yum install -y zip python3-pip python3 python3-setuptools
      - pip3 install boto3 paramiko -t .
      # - zip -r rke-runner.zip .
      # - aws s3 cp rke-runner.zip s3://rancher-aws/rke/rke-runner.zip --force
      - python3 --version
      - python3 run.py
      - echo Build completed on `date`